CREATE TABLE Planet (
    pID INT PRIMARY KEY,
    pName VARCHAR(255) NOT NULL,
    sID INT NOT NULL,
    cID INT NOT NULL,
    FOREIGN KEY (sID) REFERENCES Star(sID),
    FOREIGN KEY (cID) REFERENCES Culture(cID)
);

CREATE TABLE Star (
    sID INT PRIMARY KEY,
    sName VARCHAR(255) NOT NULL,
    sysID INT NOT NULL,
    FOREIGN KEY (sysID) REFERENCES StarSystem(sysID)
);

CREATE TABLE StarSystem (
    sysID INT PRIMARY KEY,
    sysName VARCHAR(255) NOT NULL
);

CREATE TABLE Culture (
    cID INT PRIMARY KEY,
    cName VARCHAR(255) NOT NULL
);

CREATE TABLE Neighbors (
    sID1 INT NOT NULL,
    sID2 INT NOT NULL,
    PRIMARY KEY (sID1, sID2),
    FOREIGN KEY (sID1) REFERENCES Star(sID),
    FOREIGN KEY (sID2) REFERENCES Star(sID)
);

